# @format

extends:
  - airbnb
  - prettier
plugins:
  - prettier
globals:
  document: true
rules:
  prettier/prettier: error
  newline-after-var:
    - error
    - always
  newline-before-return: error
  linebreak-style: off
  global-require: off
  react/jsx-filename-extension: off
  react/jsx-one-expression-per-line: off
